/**
 * GENERATED: stripe-product-map.ts
 *
 * Maps Stripe Price IDs to MetroReach service slugs.
 * Regenerate with: bun run src/lib/create-stripe-products.ts
 *
 * Generated: 2026-07-24T23:10:04.581Z
 * Services: 43
 */

export interface StripeProductMapping {
  slug: string;
  stripePriceId: string;
  stripeProductId: string;
  name: string;
  category: string;
  amount: number;
  recurring: boolean;
  priceLabel: string;
}

export const STRIPE_PRODUCT_MAP: StripeProductMapping[] = [
  {
    slug: "social-media-audit",
    stripePriceId: "price_1TwsDx1v80UmMrLIbypnerFp",
    stripeProductId: "prod_UwllXDhVxrNNPj",
    name: "Social Media Audit",
    category: "organic-content",
    amount: 50000,
    recurring: false,
    priceLabel: "$500 one-time",
  },
  {
    slug: "monthly-content-calendar",
    stripePriceId: "price_1TwsDx1v80UmMrLIlDPpz6kN",
    stripeProductId: "prod_UwllRMn4M39dTK",
    name: "Monthly Content Calendar",
    category: "organic-content",
    amount: 100000,
    recurring: true,
    priceLabel: "From $1,000/month",
  },
  {
    slug: "caption-writing",
    stripePriceId: "price_1TwsDy1v80UmMrLIsfyWdjbd",
    stripeProductId: "prod_Uwll1W1FJNPp4K",
    name: "Caption Writing",
    category: "organic-content",
    amount: 75000,
    recurring: true,
    priceLabel: "From $750/month",
  },
  {
    slug: "hashtag-research",
    stripePriceId: "price_1TwsDy1v80UmMrLIVG79juXu",
    stripeProductId: "prod_UwllH0j0JpvZ1G",
    name: "Hashtag Research",
    category: "organic-content",
    amount: 30000,
    recurring: false,
    priceLabel: "$300 one-time",
  },
  {
    slug: "brand-voice-development",
    stripePriceId: "price_1TwsDy1v80UmMrLIs5KqCm8e",
    stripeProductId: "prod_UwllkklHelRzHU",
    name: "Brand Voice Development",
    category: "organic-content",
    amount: 50000,
    recurring: false,
    priceLabel: "From $500 one-time",
  },
  {
    slug: "posting-schedule-optimization",
    stripePriceId: "price_1TwsDz1v80UmMrLIrLuzHMV4",
    stripeProductId: "prod_Uwll4eqvi8IkkO",
    name: "Posting Schedule Optimization",
    category: "organic-content",
    amount: 40000,
    recurring: true,
    priceLabel: "From $400/month",
  },
  {
    slug: "trend-research",
    stripePriceId: "price_1TwsDz1v80UmMrLILJ5qY6m8",
    stripeProductId: "prod_UwllA9b7fkk41L",
    name: "Trend Research",
    category: "organic-content",
    amount: 35000,
    recurring: true,
    priceLabel: "From $350/month",
  },
  {
    slug: "daily-engagement",
    stripePriceId: "price_1TwsDz1v80UmMrLI2nWZWgCr",
    stripeProductId: "prod_UwllW6okB2rbfB",
    name: "Daily Engagement",
    category: "organic-content",
    amount: 60000,
    recurring: true,
    priceLabel: "From $600/month",
  },
  {
    slug: "dm-management",
    stripePriceId: "price_1TwsE01v80UmMrLIJefPUwTk",
    stripeProductId: "prod_Uwll5xWsXLgXkP",
    name: "DM Management",
    category: "organic-content",
    amount: 40000,
    recurring: true,
    priceLabel: "From $400/month",
  },
  {
    slug: "social-listening",
    stripePriceId: "price_1TwsE01v80UmMrLIPYyd2WVd",
    stripeProductId: "prod_UwllS5TupzMb1L",
    name: "Social Listening",
    category: "organic-content",
    amount: 50000,
    recurring: true,
    priceLabel: "From $500/month",
  },
  {
    slug: "single-platform-management",
    stripePriceId: "price_1TwsE11v80UmMrLIeXeoFm4K",
    stripeProductId: "prod_UwllZDHO4fxQHT",
    name: "Single-Platform Management",
    category: "organic-content",
    amount: 80000,
    recurring: true,
    priceLabel: "From $800/month",
  },
  {
    slug: "multi-platform-management",
    stripePriceId: "price_1TwsE11v80UmMrLIdIo9YIO4",
    stripeProductId: "prod_UwllNbiFCPlHjh",
    name: "Multi-Platform Management — 5 Platforms",
    category: "organic-content",
    amount: 200000,
    recurring: true,
    priceLabel: "From $2,000/month",
  },
  {
    slug: "platform-setup-optimization",
    stripePriceId: "price_1TwsE11v80UmMrLIbQbN2u7i",
    stripeProductId: "prod_UwllPkRYgcSJOX",
    name: "Platform Setup & Optimization",
    category: "organic-content",
    amount: 75000,
    recurring: false,
    priceLabel: "From $750 one-time",
  },
  {
    slug: "profile-bio-optimization",
    stripePriceId: "price_1TwsE21v80UmMrLIpqBk4xUI",
    stripeProductId: "prod_Uwllzczsb4pR2b",
    name: "Profile/Bio Optimization",
    category: "organic-content",
    amount: 40000,
    recurring: false,
    priceLabel: "$400 one-time",
  },
  {
    slug: "meta-ads-management",
    stripePriceId: "price_1TwsE21v80UmMrLIu7qoa7sy",
    stripeProductId: "prod_UwlltsxzfuxHP4",
    name: "Meta Ads Management",
    category: "paid-advertising",
    amount: 100000,
    recurring: true,
    priceLabel: "From $1,000/month + 10% ad spend",
  },
  {
    slug: "ad-account-setup",
    stripePriceId: "price_1TwsE21v80UmMrLI9TYhDdN2",
    stripeProductId: "prod_Uwllf9fvUxaOUq",
    name: "Ad Account Setup",
    category: "paid-advertising",
    amount: 50000,
    recurring: false,
    priceLabel: "$500 one-time",
  },
  {
    slug: "ad-creative-package",
    stripePriceId: "price_1TwsE31v80UmMrLIQiF6j4O0",
    stripeProductId: "prod_Uwll1KqBi4jrN3",
    name: "Ad Creative Package",
    category: "paid-advertising",
    amount: 75000,
    recurring: true,
    priceLabel: "From $750/month",
  },
  {
    slug: "ab-testing-optimization",
    stripePriceId: "price_1TwsE31v80UmMrLIKfRlNzKo",
    stripeProductId: "prod_UwllQt2YIp8sXj",
    name: "A/B Testing & Optimization",
    category: "paid-advertising",
    amount: 50000,
    recurring: true,
    priceLabel: "From $500/month",
  },
  {
    slug: "pixel-conversion-tracking",
    stripePriceId: "price_1TwsE31v80UmMrLIxZyKtDvc",
    stripeProductId: "prod_Uwllpdqb9XPqf7",
    name: "Pixel & Conversion Tracking",
    category: "paid-advertising",
    amount: 40000,
    recurring: false,
    priceLabel: "$400 one-time",
  },
  {
    slug: "landing-page-review",
    stripePriceId: "price_1TwsE41v80UmMrLI8aH91plZ",
    stripeProductId: "prod_UwllbqU1LQG3jB",
    name: "Landing Page Review",
    category: "paid-advertising",
    amount: 35000,
    recurring: false,
    priceLabel: "$350 one-time",
  },
  {
    slug: "social-media-audit-strategy",
    stripePriceId: "price_1TwsE41v80UmMrLInyOixQua",
    stripeProductId: "prod_UwllaulQPqV5o8",
    name: "Social Media Audit",
    category: "social-strategy",
    amount: 50000,
    recurring: false,
    priceLabel: "$500 one-time",
  },
  {
    slug: "competitor-analysis",
    stripePriceId: "price_1TwsE41v80UmMrLIBEYdXZv7",
    stripeProductId: "prod_UwllQK7kKtgoLE",
    name: "Competitor Analysis",
    category: "social-strategy",
    amount: 75000,
    recurring: false,
    priceLabel: "$750 one-time",
  },
  {
    slug: "social-media-strategy",
    stripePriceId: "price_1TwsE51v80UmMrLI7T5MoktW",
    stripeProductId: "prod_Uwllo4Gz9XyOpo",
    name: "Social Media Strategy",
    category: "social-strategy",
    amount: 120000,
    recurring: false,
    priceLabel: "From $1,200 one-time",
  },
  {
    slug: "content-strategy",
    stripePriceId: "price_1TwsE51v80UmMrLIZf1UMIkP",
    stripeProductId: "prod_UwllmU7nOpfc65",
    name: "Content Strategy",
    category: "social-strategy",
    amount: 100000,
    recurring: false,
    priceLabel: "From $1,000 one-time",
  },
  {
    slug: "campaign-strategy",
    stripePriceId: "price_1TwsE51v80UmMrLIQHJ2FQyP",
    stripeProductId: "prod_Uwll2athh0fZzE",
    name: "Campaign Strategy",
    category: "social-strategy",
    amount: 80000,
    recurring: false,
    priceLabel: "From $800 one-time",
  },
  {
    slug: "audience-research",
    stripePriceId: "price_1TwsE61v80UmMrLIrAbEeRpo",
    stripeProductId: "prod_Uwll76fOXU8DqX",
    name: "Audience Research",
    category: "social-strategy",
    amount: 60000,
    recurring: false,
    priceLabel: "From $600 one-time",
  },
  {
    slug: "organic-growth-strategy",
    stripePriceId: "price_1TwsE61v80UmMrLIbuuJZeuJ",
    stripeProductId: "prod_Uwllhs5YFLaNAW",
    name: "Organic Growth Strategy",
    category: "social-strategy",
    amount: 70000,
    recurring: true,
    priceLabel: "From $700/month",
  },
  {
    slug: "monthly-strategy-reviews",
    stripePriceId: "price_1TwsE71v80UmMrLI7ajLJDLi",
    stripeProductId: "prod_Uwllv4IzZ8L3zu",
    name: "Monthly Strategy Reviews",
    category: "social-strategy",
    amount: 50000,
    recurring: true,
    priceLabel: "From $500/month",
  },
  {
    slug: "monthly-performance-reports",
    stripePriceId: "price_1TwsE71v80UmMrLIGCovGtU0",
    stripeProductId: "prod_Uwllt6j8F9XXAs",
    name: "Monthly Performance Reports",
    category: "analytics-reporting",
    amount: 50000,
    recurring: true,
    priceLabel: "From $500/month",
  },
  {
    slug: "weekly-performance-summaries",
    stripePriceId: "price_1TwsE71v80UmMrLIyLL3Jr29",
    stripeProductId: "prod_Uwll3VCHNcQinP",
    name: "Weekly Performance Summaries",
    category: "analytics-reporting",
    amount: 35000,
    recurring: true,
    priceLabel: "From $350/month",
  },
  {
    slug: "kpi-dashboard-setup",
    stripePriceId: "price_1TwsE81v80UmMrLIVOxjvWln",
    stripeProductId: "prod_UwllzopaU4yUyp",
    name: "KPI Dashboard Setup",
    category: "analytics-reporting",
    amount: 75000,
    recurring: false,
    priceLabel: "$750 one-time",
  },
  {
    slug: "executive-reports",
    stripePriceId: "price_1TwsE81v80UmMrLIFvhg1zw6",
    stripeProductId: "prod_UwllQ8Jmp6VMCb",
    name: "Executive Reports",
    category: "analytics-reporting",
    amount: 60000,
    recurring: true,
    priceLabel: "From $600/month",
  },
  {
    slug: "competitor-benchmarking",
    stripePriceId: "price_1TwsE81v80UmMrLImSHhdV65",
    stripeProductId: "prod_UwllpqyqIIjcKj",
    name: "Competitor Benchmarking",
    category: "analytics-reporting",
    amount: 50000,
    recurring: true,
    priceLabel: "From $500/month",
  },
  {
    slug: "community-management",
    stripePriceId: "price_1TwsE91v80UmMrLIuFk27Rjr",
    stripeProductId: "prod_UwllNGMcQhr5yD",
    name: "Community Management",
    category: "community-management",
    amount: 120000,
    recurring: true,
    priceLabel: "From $1,200/month",
  },
  {
    slug: "daily-monitoring-engagement",
    stripePriceId: "price_1TwsE91v80UmMrLIMNe67VYA",
    stripeProductId: "prod_UwllCt3RUM0lsr",
    name: "Daily Monitoring & Engagement",
    category: "community-management",
    amount: 60000,
    recurring: true,
    priceLabel: "From $600/month",
  },
  {
    slug: "comment-dm-response",
    stripePriceId: "price_1TwsE91v80UmMrLIbONKJtx3",
    stripeProductId: "prod_Uwll8lyzMIevZo",
    name: "Comment & DM Response",
    category: "community-management",
    amount: 40000,
    recurring: true,
    priceLabel: "From $400/month",
  },
  {
    slug: "review-management",
    stripePriceId: "price_1TwsEA1v80UmMrLICXOI9pfc",
    stripeProductId: "prod_Uwllr20ieuyJ59",
    name: "Review Management",
    category: "community-management",
    amount: 35000,
    recurring: true,
    priceLabel: "From $350/month",
  },
  {
    slug: "social-listening-community",
    stripePriceId: "price_1TwsEA1v80UmMrLIgNkPjHtH",
    stripeProductId: "prod_Uwlli4R0PHg6LP",
    name: "Social Listening",
    category: "community-management",
    amount: 50000,
    recurring: true,
    priceLabel: "From $500/month",
  },
  {
    slug: "influencer-research",
    stripePriceId: "price_1TwsEB1v80UmMrLIyBcnadaX",
    stripeProductId: "prod_UwllkRWQMPb38o",
    name: "Influencer Research",
    category: "community-management",
    amount: 75000,
    recurring: true,
    priceLabel: "From $750/month",
  },
  {
    slug: "community-engagement-templates",
    stripePriceId: "price_1TwsEB1v80UmMrLIsKN9upX6",
    stripeProductId: "prod_Uwllk9fE9frhes",
    name: "Community Engagement Templates",
    category: "community-management",
    amount: 30000,
    recurring: false,
    priceLabel: "$300 one-time",
  },
  {
    slug: "platform-setup-community",
    stripePriceId: "price_1TwsEB1v80UmMrLI6PY5T1Bi",
    stripeProductId: "prod_UwllUNmnku1IJR",
    name: "Platform Setup & Optimization",
    category: "community-management",
    amount: 75000,
    recurring: false,
    priceLabel: "From $750 one-time",
  },
  {
    slug: "social-inbox-management",
    stripePriceId: "price_1TwsEC1v80UmMrLIUqPV21WV",
    stripeProductId: "prod_Uwll7zKpuPVlA6",
    name: "Social Inbox Management",
    category: "community-management",
    amount: 50000,
    recurring: true,
    priceLabel: "From $500/month",
  },
  {
    slug: "social-inbox-design",
    stripePriceId: "price_1TwsEC1v80UmMrLIU8rpLrcd",
    stripeProductId: "prod_UwllJatlQfzC9W",
    name: "Social Inbox Design",
    category: "community-management",
    amount: 60000,
    recurring: false,
    priceLabel: "From $600 one-time",
  },
  {
    slug: "vip-daily",
    stripePriceId: "price_1Txrn51v80UmMrLIol8Tln4b",
    stripeProductId: "prod_UxEawjHXDUZA8g",
    name: "Aggressive Daily Organic — VIP",
    category: "organic-content",
    amount: 850000,
    recurring: true,
    priceLabel: "$8,500/month",
  },
  {
    slug: "premium-growth-audit",
    stripePriceId: "price_1TwKxKDGk9TbScamUD3JHGFO",
    stripeProductId: "prod_UwDOA7SlmyFndE",
    name: "Premium Growth Audit",
    category: "strategy",
    amount: 49500,
    recurring: false,
    priceLabel: "$495 one-time",
  },
];

/** Lookup a mapping by service slug */
export function getMappingBySlug(slug: string): StripeProductMapping | undefined {
  return STRIPE_PRODUCT_MAP.find((m) => m.slug === slug);
}

/** Lookup a mapping by Stripe Price ID */
export function getMappingByPriceId(priceId: string): StripeProductMapping | undefined {
  return STRIPE_PRODUCT_MAP.find((m) => m.stripePriceId === priceId);
}

/** PRICE_TO_SERVICE: Stripe Price ID → { name, slug } (for webhook) */
export const PRICE_TO_SERVICE: Record<string, { name: string; slug: string }> = {
  "price_1TwsDx1v80UmMrLIbypnerFp": { name: "Social Media Audit", slug: "social-media-audit" },
  "price_1TwsDx1v80UmMrLIlDPpz6kN": { name: "Monthly Content Calendar", slug: "monthly-content-calendar" },
  "price_1TwsDy1v80UmMrLIsfyWdjbd": { name: "Caption Writing", slug: "caption-writing" },
  "price_1TwsDy1v80UmMrLIVG79juXu": { name: "Hashtag Research", slug: "hashtag-research" },
  "price_1TwsDy1v80UmMrLIs5KqCm8e": { name: "Brand Voice Development", slug: "brand-voice-development" },
  "price_1TwsDz1v80UmMrLIrLuzHMV4": { name: "Posting Schedule Optimization", slug: "posting-schedule-optimization" },
  "price_1TwsDz1v80UmMrLILJ5qY6m8": { name: "Trend Research", slug: "trend-research" },
  "price_1TwsDz1v80UmMrLI2nWZWgCr": { name: "Daily Engagement", slug: "daily-engagement" },
  "price_1TwsE01v80UmMrLIJefPUwTk": { name: "DM Management", slug: "dm-management" },
  "price_1TwsE01v80UmMrLIPYyd2WVd": { name: "Social Listening", slug: "social-listening" },
  "price_1TwsE11v80UmMrLIeXeoFm4K": { name: "Single-Platform Management", slug: "single-platform-management" },
  "price_1TwsE11v80UmMrLIdIo9YIO4": { name: "Multi-Platform Management — 5 Platforms", slug: "multi-platform-management" },
  "price_1TwsE11v80UmMrLIbQbN2u7i": { name: "Platform Setup & Optimization", slug: "platform-setup-optimization" },
  "price_1TwsE21v80UmMrLIpqBk4xUI": { name: "Profile/Bio Optimization", slug: "profile-bio-optimization" },
  "price_1TwsE21v80UmMrLIu7qoa7sy": { name: "Meta Ads Management", slug: "meta-ads-management" },
  "price_1TwsE21v80UmMrLI9TYhDdN2": { name: "Ad Account Setup", slug: "ad-account-setup" },
  "price_1TwsE31v80UmMrLIQiF6j4O0": { name: "Ad Creative Package", slug: "ad-creative-package" },
  "price_1TwsE31v80UmMrLIKfRlNzKo": { name: "A/B Testing & Optimization", slug: "ab-testing-optimization" },
  "price_1TwsE31v80UmMrLIxZyKtDvc": { name: "Pixel & Conversion Tracking", slug: "pixel-conversion-tracking" },
  "price_1TwsE41v80UmMrLI8aH91plZ": { name: "Landing Page Review", slug: "landing-page-review" },
  "price_1TwsE41v80UmMrLInyOixQua": { name: "Social Media Audit", slug: "social-media-audit-strategy" },
  "price_1TwsE41v80UmMrLIBEYdXZv7": { name: "Competitor Analysis", slug: "competitor-analysis" },
  "price_1TwsE51v80UmMrLI7T5MoktW": { name: "Social Media Strategy", slug: "social-media-strategy" },
  "price_1TwsE51v80UmMrLIZf1UMIkP": { name: "Content Strategy", slug: "content-strategy" },
  "price_1TwsE51v80UmMrLIQHJ2FQyP": { name: "Campaign Strategy", slug: "campaign-strategy" },
  "price_1TwsE61v80UmMrLIrAbEeRpo": { name: "Audience Research", slug: "audience-research" },
  "price_1TwsE61v80UmMrLIbuuJZeuJ": { name: "Organic Growth Strategy", slug: "organic-growth-strategy" },
  "price_1TwsE71v80UmMrLI7ajLJDLi": { name: "Monthly Strategy Reviews", slug: "monthly-strategy-reviews" },
  "price_1TwsE71v80UmMrLIGCovGtU0": { name: "Monthly Performance Reports", slug: "monthly-performance-reports" },
  "price_1TwsE71v80UmMrLIyLL3Jr29": { name: "Weekly Performance Summaries", slug: "weekly-performance-summaries" },
  "price_1TwsE81v80UmMrLIVOxjvWln": { name: "KPI Dashboard Setup", slug: "kpi-dashboard-setup" },
  "price_1TwsE81v80UmMrLIFvhg1zw6": { name: "Executive Reports", slug: "executive-reports" },
  "price_1TwsE81v80UmMrLImSHhdV65": { name: "Competitor Benchmarking", slug: "competitor-benchmarking" },
  "price_1TwsE91v80UmMrLIuFk27Rjr": { name: "Community Management", slug: "community-management" },
  "price_1TwsE91v80UmMrLIMNe67VYA": { name: "Daily Monitoring & Engagement", slug: "daily-monitoring-engagement" },
  "price_1TwsE91v80UmMrLIbONKJtx3": { name: "Comment & DM Response", slug: "comment-dm-response" },
  "price_1TwsEA1v80UmMrLICXOI9pfc": { name: "Review Management", slug: "review-management" },
  "price_1TwsEA1v80UmMrLIgNkPjHtH": { name: "Social Listening", slug: "social-listening-community" },
  "price_1TwsEB1v80UmMrLIyBcnadaX": { name: "Influencer Research", slug: "influencer-research" },
  "price_1TwsEB1v80UmMrLIsKN9upX6": { name: "Community Engagement Templates", slug: "community-engagement-templates" },
  "price_1TwsEB1v80UmMrLI6PY5T1Bi": { name: "Platform Setup & Optimization", slug: "platform-setup-community" },
  "price_1TwsEC1v80UmMrLIUqPV21WV": { name: "Social Inbox Management", slug: "social-inbox-management" },
  "price_1TwsEC1v80UmMrLIU8rpLrcd": { name: "Social Inbox Design", slug: "social-inbox-design" },
  "price_1Txrn51v80UmMrLIol8Tln4b": { name: "Aggressive Daily Organic — VIP", slug: "vip-daily" },
  "price_1TwKxKDGk9TbScamUD3JHGFO": { name: "Premium Growth Audit", slug: "premium-growth-audit" },
};
