import { useEffect, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { createServerFn } from "@tanstack/react-start";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { ArrowRight, CheckCircle, WarningCircle, XCircle, Star, Lightning, Target, ChartLineUp, Users, Medal, ShoppingCart, Spinner } from "@phosphor-icons/react";
import { Container } from "~/components/Container";
import { Button } from "~/components/Button";

// Types
interface ProfileScore { profilePicture: { score: number; observation: string }; bio: { score: number; observation: string }; bioLength: { score: number; observation: string }; websiteLink: { score: number; observation: string }; coverImage: { score: number; observation: string }; category: { score: number; observation: string }; total: number; }
interface ConsistencyScore { postCount: number; score: number; gaps: number; gapPenalty: number; total: number; observation: string; }
interface EngagementScore { hasEngagement: boolean; hasReplies: boolean; total: number; observation: string; }
interface CompetitiveScore { hasReviews: boolean; hasStories: boolean; hasReels: boolean; total: number; observation: string; }
interface QuickWin { issue: string; fix: string; timeEstimate: string; impactLevel: "High" | "Medium"; }
interface ServiceRec { slug: string; name: string; reason: string; }

interface AuditResult {
  id: string; formData: { businessName: string; websiteUrl: string; industry: string; facebookUrl: string; instagramUrl: string; tiktokUrl: string; linkedinUrl: string; name: string; email: string; phone: string; goals: string; };
  platforms: any[]; scores: { profileCompleteness: { total: number; breakdown: Record<string, ProfileScore> }; postingConsistency: { total: number; breakdown: Record<string, ConsistencyScore> }; brandCohesion: { total: number; observation: string }; engagementHealth: { total: number; breakdown: Record<string, EngagementScore> }; competitiveSignal: { total: number; breakdown: Record<string, CompetitiveScore> }; overall: number; };
  strengths: string[]; weaknesses: string[]; quickWins: QuickWin[]; serviceRecommendations: ServiceRec[]; timestamp: string;
}

const loadAudit = createServerFn({ method: "GET" }).validator((id: string) => id).handler(async ({ data: id }) => {
  const safeId = id.replace(/[^a-zA-Z0-9\-]/g, "");
  try { const raw = await readFile(join("/home/team/shared/audits", `${safeId}.json`), "utf-8"); return JSON.parse(raw) as AuditResult; } catch { return null; }
});

export const Route = createFileRoute("/audit-report")({ component: AuditReportPage });

function ScoreColor({ score, max = 25 }: { score: number; max?: number }) { const pct = max > 0 ? score / max : 0; if (pct >= 0.7) return <span className="text-success font-bold">{score}/{max}</span>; if (pct >= 0.4) return <span className="text-warning font-bold">{score}/{max}</span>; return <span className="text-error font-bold">{score}/{max}</span>; }
function ScoreBadge({ score }: { score: number }) { let color: string; let label: string; if (score >= 70) { color = "text-success"; label = "Strong"; } else if (score >= 40) { color = "text-warning"; label = "Needs Work"; } else { color = "text-error"; label = "Critical"; } return (<span className={`inline-flex items-center gap-1.5 text-sm font-semibold ${color}`}><span className={`w-2 h-2 rounded-full ${score >= 70 ? "bg-success" : score >= 40 ? "bg-warning" : "bg-error"}`} />{label}</span>); }
function StatusIcon({ score, max }: { score: number; max: number }) { const pct = max > 0 ? score / max : 0; if (pct >= 0.7) return <CheckCircle size={18} weight="fill" className="text-success flex-shrink-0" />; if (pct >= 0.4) return <WarningCircle size={18} weight="fill" className="text-warning flex-shrink-0" />; return <XCircle size={18} weight="fill" className="text-error flex-shrink-0" />; }

const categoryIcons: Record<string, any> = { completeness: CheckCircle, consistency: ChartLineUp, cohesion: Users, engagement: Star, competitive: Target };
const categoryLabels: Record<string, string> = { completeness: "Profile Completeness", consistency: "Posting Consistency", cohesion: "Brand Cohesion", engagement: "Engagement Health", competitive: "Competitive Signal" };
const categoryMax: Record<string, number> = { completeness: 25, consistency: 25, cohesion: 20, engagement: 15, competitive: 15 };

function AuditReportPage() {
  const [audit, setAudit] = useState<AuditResult | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    const id = params.get("id");
    if (!id) { setError("No audit ID provided."); setLoading(false); return; }
    loadAudit({ data: id }).then((data) => {
      if (!data) { setError("Report not found. It may have expired."); } else { setAudit(data); }
      setLoading(false);
    }).catch(() => { setError("Failed to load report."); setLoading(false); });
  }, []);

  if (loading) return (<div className="min-h-dvh flex flex-col items-center justify-center gap-4 px-6 text-center bg-bg-root"><Spinner size={32} weight="bold" className="animate-spin text-brand-primary" /><p className="text-text-secondary">Loading your audit report...</p></div>);
  if (error || !audit) return (<div className="min-h-dvh flex flex-col items-center justify-center gap-6 px-6 text-center bg-bg-root"><h1 className="text-4xl md:text-5xl font-bold font-heading text-text-primary">Report not found.</h1><p className="text-lg text-text-secondary max-w-md">{error || "This report doesn't exist."}</p><a href="/audit" className="inline-flex items-center gap-2 rounded-full bg-brand-primary text-text-primary px-8 py-3.5 text-base font-semibold hover:bg-gradient-to-r hover:from-brand-primary hover:to-brand-accent transition-all duration-200">Run a new audit →</a></div>);

  const { formData, platforms, scores, strengths, weaknesses, quickWins, serviceRecommendations, timestamp } = audit;
  const auditDate = new Date(timestamp).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  const overallColor = scores.overall >= 70 ? "text-success" : scores.overall >= 40 ? "text-warning" : "text-error";
  const categoryKeys = ["completeness", "consistency", "cohesion", "engagement", "competitive"] as const;
  const categoryScores: Record<string, number> = { completeness: scores.profileCompleteness.total, consistency: scores.postingConsistency.total, cohesion: scores.brandCohesion.total, engagement: scores.engagementHealth.total, competitive: scores.competitiveSignal.total };

  return (<main>
    {/* Header */}
    <section className="relative py-16 lg:py-24 bg-bg-root overflow-hidden border-b border-border-subtle"><div className="absolute inset-0 bg-[radial-gradient(ellipse_500px_at_50%_50%,rgba(59,130,246,0.04),transparent)] pointer-events-none" /><Container className="relative z-10"><div className="max-w-3xl mx-auto"><p className="text-xs font-medium text-text-muted uppercase tracking-widest mb-4">Social Media Audit &bull; {auditDate}</p><p className="text-sm text-text-secondary mb-2">Prepared for</p><h1 className="text-3xl md:text-4xl lg:text-5xl font-bold font-heading text-text-primary tracking-tight mb-8">{formData.businessName}</h1><div className="flex items-center gap-6 p-6 rounded-2xl bg-bg-surface-raised border border-border-subtle"><div className="flex-shrink-0"><div className={`text-6xl md:text-7xl font-bold font-heading ${overallColor} tabular-nums`}>{scores.overall}</div><p className="text-sm text-text-muted mt-1">out of 100</p></div><div className="flex-1 min-w-0"><ScoreBadge score={scores.overall} /><p className="text-sm text-text-secondary mt-2 leading-relaxed">{scores.overall >= 70 ? `${formData.businessName} has a solid social media foundation.` : scores.overall >= 40 ? `${formData.businessName} has the basics in place, but there are clear gaps costing you leads.` : `${formData.businessName}'s social media presence needs foundational work. Every improvement translates directly to more visibility, trust, and leads.`}</p></div></div></div></Container></section>

    {/* Score Breakdown */}
    <section className="py-16 bg-bg-surface"><Container><div className="max-w-3xl mx-auto"><h2 className="text-2xl font-bold font-heading text-text-primary mb-8">Score Breakdown</h2><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">{categoryKeys.map((key) => { const Icon = categoryIcons[key]; const s = categoryScores[key]; const m = categoryMax[key]; const pct = m > 0 ? s / m : 0; const bc = pct >= 0.7 ? "bg-success" : pct >= 0.4 ? "bg-warning" : "bg-error"; return (<div key={key} className="rounded-2xl bg-bg-surface-raised border border-border-subtle p-5"><div className="flex items-center gap-3 mb-3">{Icon && <Icon size={22} weight="fill" className="text-brand-primary flex-shrink-0" />}<span className="text-sm font-medium text-text-secondary">{categoryLabels[key]}</span></div><div className="flex items-baseline gap-2 mb-3"><span className={`text-2xl font-bold font-heading tabular-nums ${pct >= 0.7 ? "text-success" : pct >= 0.4 ? "text-warning" : "text-error"}`}>{s}</span><span className="text-sm text-text-muted">/ {m}</span></div><div className="w-full h-1.5 rounded-full bg-bg-surface-high overflow-hidden"><div className={`h-full rounded-full transition-all duration-700 ${bc}`} style={{ width: `${Math.max(pct * 100, 2)}%` }} /></div></div>); })}</div></div></Container></section>

    {/* Platform-by-Platform */}
    {platforms.length > 0 && (<section className="py-16 bg-bg-root border-t border-border-subtle"><Container><div className="max-w-3xl mx-auto"><h2 className="text-2xl font-bold font-heading text-text-primary mb-8">Platform-by-Platform Analysis</h2>{platforms.map((p: any) => { const pf = scores.profileCompleteness.breakdown[p.platform]; const pc = scores.postingConsistency.breakdown[p.platform]; const eh = scores.engagementHealth.breakdown[p.platform]; const cs = scores.competitiveSignal.breakdown[p.platform]; return (<div key={p.platform} className="mb-8 rounded-2xl bg-bg-surface-raised border border-border-subtle overflow-hidden"><div className="p-6 border-b border-border-subtle"><div className="flex items-center justify-between"><div><h3 className="text-lg font-semibold font-heading text-text-primary">{p.platform}</h3>{p.handle && <p className="text-sm text-text-muted mt-0.5">@{p.handle}</p>}</div>{p.url && <a href={p.url} target="_blank" rel="noopener noreferrer" className="text-sm text-brand-primary hover:text-brand-accent transition-colors">View Profile ↗</a>}</div></div>
      {pf && (<div className="p-6 border-b border-border-subtle"><div className="flex items-center gap-2 mb-4"><CheckCircle size={18} weight="fill" className="text-brand-primary" /><h4 className="text-sm font-semibold text-text-primary">Profile Completeness — <ScoreColor score={pf.total} max={25} /></h4></div><div className="space-y-4">{[{ k: "profilePicture", l: "Profile Picture", i: pf.profilePicture, max: 5 },{ k: "bio", l: "Bio / Description", i: pf.bio, max: 5 },{ k: "bioLength", l: "Bio Length", i: pf.bioLength, max: 3 },{ k: "websiteLink", l: "Website Link", i: pf.websiteLink, max: 4 },{ k: "coverImage", l: "Cover / Banner", i: pf.coverImage, max: 4 },{ k: "category", l: "Business Category", i: pf.category, max: 4 }].map(({ k, l, i, max }) => (<div key={k} className="flex items-start gap-3"><StatusIcon score={i.score} max={max} /><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><span className="text-sm font-medium text-text-primary">{l}</span><span className="text-xs text-text-muted tabular-nums">{i.score}/{max}</span></div><p className="text-sm text-text-secondary mt-1 leading-relaxed">{i.observation}</p></div></div>))}</div></div>)}
      {pc && (<div className="p-6 border-b border-border-subtle"><div className="flex items-center gap-2 mb-4"><ChartLineUp size={18} weight="fill" className="text-brand-primary" /><h4 className="text-sm font-semibold text-text-primary">Posting Consistency — <ScoreColor score={pc.total} max={25} /></h4></div><div className="flex items-center gap-4 mb-3"><div className="text-center"><div className="text-2xl font-bold font-heading text-text-primary tabular-nums">{pc.postCount}</div><div className="text-xs text-text-muted">posts / 30 days</div></div>{pc.gaps > 0 && <div className="text-center"><div className="text-2xl font-bold font-heading text-warning tabular-nums">{pc.gaps}</div><div className="text-xs text-text-muted">gaps &gt; 7 days</div></div>}</div><p className="text-sm text-text-secondary leading-relaxed">{pc.observation}</p></div>)}
      {eh && (<div className="p-6 border-b border-border-subtle"><div className="flex items-center gap-2 mb-3"><Star size={18} weight="fill" className="text-brand-primary" /><h4 className="text-sm font-semibold text-text-primary">Engagement Health — <ScoreColor score={eh.total} max={15} /></h4></div><div className="flex items-center gap-4 mb-3"><span className={`text-xs font-medium px-2.5 py-1 rounded-full ${eh.hasEngagement ? "bg-success/15 text-success" : "bg-error/15 text-error"}`}>{eh.hasEngagement ? "Engagement Detected" : "No Engagement"}</span><span className={`text-xs font-medium px-2.5 py-1 rounded-full ${eh.hasReplies ? "bg-success/15 text-success" : "bg-error/15 text-error"}`}>{eh.hasReplies ? "Replies Detected" : "No Replies"}</span></div><p className="text-sm text-text-secondary leading-relaxed">{eh.observation}</p></div>)}
      {cs && (<div className="p-6"><div className="flex items-center gap-2 mb-3"><Target size={18} weight="fill" className="text-brand-primary" /><h4 className="text-sm font-semibold text-text-primary">Competitive Signal — <ScoreColor score={cs.total} max={15} /></h4></div><div className="flex flex-wrap items-center gap-2 mb-3"><span className={`text-xs font-medium px-2.5 py-1 rounded-full ${cs.hasReviews ? "bg-success/15 text-success" : "bg-error/15 text-error"}`}>Reviews: {cs.hasReviews ? "Yes" : "None"}</span><span className={`text-xs font-medium px-2.5 py-1 rounded-full ${cs.hasStories ? "bg-success/15 text-success" : "bg-error/15 text-error"}`}>Stories: {cs.hasStories ? "Active" : "None"}</span><span className={`text-xs font-medium px-2.5 py-1 rounded-full ${cs.hasReels ? "bg-success/15 text-success" : "bg-error/15 text-error"}`}>Video/Reels: {cs.hasReels ? "Active" : "None"}</span></div><p className="text-sm text-text-secondary leading-relaxed">{cs.observation}</p></div>)}
    </div>); })}</div></Container></section>)}

    {/* Brand Cohesion */}
    <section className="py-16 bg-bg-surface border-t border-border-subtle"><Container><div className="max-w-3xl mx-auto"><h2 className="text-2xl font-bold font-heading text-text-primary mb-6">Brand Cohesion</h2><div className="rounded-2xl bg-bg-surface-raised border border-border-subtle p-6"><div className="flex items-center gap-3 mb-4"><Users size={22} weight="fill" className="text-brand-primary" /><span className="text-sm font-semibold text-text-primary">Brand Cohesion Score — <ScoreColor score={scores.brandCohesion.total} max={20} /></span></div><p className="text-sm text-text-secondary leading-relaxed">{scores.brandCohesion.observation}</p></div></div></Container></section>

    {/* Strengths & Weaknesses */}
    <section className="py-16 bg-bg-root border-t border-border-subtle"><Container><div className="max-w-3xl mx-auto"><div className="grid grid-cols-1 md:grid-cols-2 gap-8"><div><h2 className="text-xl font-bold font-heading text-text-primary mb-6 flex items-center gap-2"><Medal size={22} weight="fill" className="text-brand-accent" />Top Strengths</h2><div className="space-y-4">{strengths.map((s, i) => (<div key={i} className="rounded-xl bg-bg-surface-raised border border-border-subtle p-4"><div className="flex items-start gap-3"><span className="flex-shrink-0 w-6 h-6 rounded-full bg-success/15 flex items-center justify-center"><CheckCircle size={14} weight="fill" className="text-success" /></span><p className="text-sm text-text-secondary leading-relaxed">{s}</p></div></div>))}</div></div><div><h2 className="text-xl font-bold font-heading text-text-primary mb-6 flex items-center gap-2"><WarningCircle size={22} weight="fill" className="text-warning" />Key Weaknesses</h2><div className="space-y-4">{weaknesses.map((w, i) => (<div key={i} className="rounded-xl bg-bg-surface-raised border border-border-subtle p-4"><div className="flex items-start gap-3"><span className="flex-shrink-0 w-6 h-6 rounded-full bg-warning/15 flex items-center justify-center"><WarningCircle size={14} weight="fill" className="text-warning" /></span><p className="text-sm text-text-secondary leading-relaxed">{w}</p></div></div>))}</div></div></div></div></Container></section>

    {/* Quick Wins */}
    <section className="py-16 bg-bg-surface border-t border-border-subtle"><Container><div className="max-w-3xl mx-auto"><h2 className="text-2xl font-bold font-heading text-text-primary mb-2">Quick Wins</h2><p className="text-text-secondary mb-8">Three specific fixes you can implement today. No budget required.</p><div className="space-y-4">{quickWins.map((win, i) => (<div key={i} className="rounded-2xl bg-bg-surface-raised border border-border-subtle p-6"><div className="flex items-start gap-4"><div className="flex-shrink-0 w-10 h-10 rounded-xl bg-brand-primary/10 flex items-center justify-center"><Lightning size={20} weight="fill" className="text-brand-accent" /></div><div className="flex-1 min-w-0"><div className="flex items-center gap-3 mb-2"><span className="text-sm font-semibold text-text-primary">Quick Win #{i + 1}</span><span className={`text-xs font-medium px-2 py-0.5 rounded-full ${win.impactLevel === "High" ? "bg-success/15 text-success" : "bg-warning/15 text-warning"}`}>{win.impactLevel} Impact</span><span className="text-xs text-text-muted">{win.timeEstimate}</span></div><p className="text-sm text-text-secondary mb-3"><span className="font-semibold text-text-primary">Issue:</span> {win.issue}</p><p className="text-sm text-text-secondary"><span className="font-semibold text-text-primary">Fix:</span> {win.fix}</p></div></div></div>))}</div></div></Container></section>

    {/* Service Recommendations */}
    <section className="py-16 bg-bg-root border-t border-border-subtle"><Container><div className="max-w-3xl mx-auto"><h2 className="text-2xl font-bold font-heading text-text-primary mb-2">Service Recommendations</h2><p className="text-text-secondary mb-8">Based on your scores and gaps, here's what would move the needle fastest.</p><div className="space-y-5">{serviceRecommendations.map((rec, i) => (<div key={i} className="rounded-2xl bg-bg-surface-raised border border-border-subtle p-6"><div className="flex items-start gap-4"><div className="flex-shrink-0 w-10 h-10 rounded-xl bg-brand-primary/10 flex items-center justify-center"><ShoppingCart size={20} weight="fill" className="text-brand-primary" /></div><div className="flex-1 min-w-0"><h3 className="text-base font-semibold font-heading text-text-primary mb-2">{rec.name}</h3><p className="text-sm text-text-secondary leading-relaxed">{rec.reason}</p></div></div></div>))}</div></div></Container></section>

    {/* CTA */}
    <section className="py-16 bg-bg-surface border-t border-border-subtle"><Container><div className="max-w-xl mx-auto text-center"><h2 className="text-2xl font-bold font-heading text-text-primary mb-4">Ready to implement these recommendations?</h2><p className="text-text-secondary mb-8">MetroReach Media can handle this for you. Our team of specialists manages every dimension of social media — strategy, creative, posting, engagement, and analytics — so you get the results without the overhead.</p><div className="flex flex-col sm:flex-row items-center justify-center gap-4"><Button href="/book">Book a Strategy Call<ArrowRight size={18} weight="bold" /></Button><Button href="/services" variant="ghost">Or browse our services</Button></div><p className="text-xs text-text-muted mt-8 pt-8 border-t border-border-subtle">Prepared by MetroReach Media. Questions? <a href="/contact" className="text-brand-primary hover:text-brand-accent transition-colors">Contact us</a>.</p></div></Container></section>
  </main>);
}
