/**
 * MetroReach Media — Social Graphics Generator (v2: Text Overlay Pipeline)
 *
 * Pipeline:
 *   1. DALL-E generates CLEAN background (NO text, NO letters)
 *   2. overlay-text.py overlays guaranteed-correct text (no hallucinations)
 *   3. Final composite saved to public/social/
 *
 * Text hallucinations are eliminated forever — text is code-generated by Pillow,
 * not AI-generated by DALL-E.
 *
 * Usage: bun run scripts/generate-social-graphics.ts
 *
 * Prerequisites:
 *   - Dev server running on port 3000 (bun run dev)
 *   - OPENAI_API_KEY set in .env.local
 *   - Python 3 + Pillow installed (python3 -c "from PIL import Image")
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync, unlinkSync } from "node:fs";
import { join } from "node:path";
import { spawnSync } from "node:child_process";
import { auditImage } from "./audit-images.js";

// ── Types ───────────────────────────────────────────────────────────────────

interface PostTask {
  num: number;
  platform: "IG" | "FB";
  day: string;
  pillar: string;
  hook: string;
  filename: string;
  creativeBrief: string;
  size: "1024x1024" | "1792x1024";
  prompt: string;
}

// ── Constants ────────────────────────────────────────────────────────────────

const API_BASE = "https://www.metroreachagency.com";
const OUTPUT_DIR = "/home/team/shared/site/public/social";
const CALENDAR_PATH = "/home/team/shared/social/content-calendar-week-1.md";
const POSTS_PATH = "/home/team/shared/social/posts-week-1.md";
const OVERLAY_SCRIPT = "/home/team/shared/site/scripts/overlay-text.py";

const SIZE_FB: "1792x1024" = "1792x1024";
const SIZE_IG: "1024x1024" = "1024x1024";
const QUALITY = "low";

// ── Helpers ──────────────────────────────────────────────────────────────────

function extractKV(line: string, key: string): string {
  const re = new RegExp(`\\*\\*${key}\\*\\*[:\\s]+(.+?)`, "i");
  const m = line.match(re);
  return m ? m[1].trim() : "";
}

function sleep(ms: number): Promise<void> {
  return new Promise((r) => setTimeout(r, ms));
}

// ── Step 1: Parse posts-week-1.md for filename mapping ──────────────────────

function parseFilenames(): Map<number, string> {
  const content = readFileSync(POSTS_PATH, "utf-8");
  const map = new Map<number, string>();

  const postHeaderRe = /### Post (\d+)\s*·/g;
  let m: RegExpExecArray | null;

  while ((m = postHeaderRe.exec(content)) !== null) {
    const num = parseInt(m[1], 10);
    const startIdx = m.index;
    const nextHeaderIdx = content.indexOf("\n###", startIdx + 10);
    const blockEnd = nextHeaderIdx === -1 ? content.length : nextHeaderIdx;
    const block = content.slice(startIdx, blockEnd);

    const imageMatch = block.match(/\*\*Image:\*\*\s*`([^`]+\.webp)`/);
    if (imageMatch) {
      map.set(num, imageMatch[1]);
    }
  }

  return map;
}

// ── Step 2: Parse content-calendar-week-1.md for posts needing graphics ─────

function parseCalendarPosts(): PostTask[] {
  const content = readFileSync(CALENDAR_PATH, "utf-8");
  const filenameMap = parseFilenames();
  const tasks: PostTask[] = [];

  const sections = content.split(/(?=### Post \d+ ·)/g);

  for (const section of sections) {
    const headerMatch = section.match(/### Post (\d+)\s*·\s*(.+?)\s*·\s*(.+)/);
    if (!headerMatch) continue;

    const num = parseInt(headerMatch[1], 10);
    const platformDay = headerMatch[2].trim();
    const pillarRaw = headerMatch[3].trim();

    const platformMatch = platformDay.match(/(Instagram|Facebook|LinkedIn)/i);
    if (!platformMatch) continue;
    const platformFull = platformMatch[1].toLowerCase();
    if (platformFull === "linkedin") continue;

    const platform = platformFull === "instagram" ? "IG" : "FB";

    const hasCustom = section.includes("🎨");
    const hasTemplate = section.includes("♻️");
    if (!hasCustom && !hasTemplate) continue;

    const lines = section.split("\n");
    let hook = "";
    let creativeBrief = "";
    let inBrief = false;

    for (const line of lines) {
      if (line.startsWith("**Hook:**")) {
        hook = extractKV(line, "Hook");
      }
      if (line.includes("**Creative brief:**")) {
        inBrief = true;
        creativeBrief = line.replace(/.*\*\*Creative brief:\*\*\s*/, "").trim();
        continue;
      }
      if (inBrief) {
        if (line.startsWith("---") || line.startsWith("## ") || line.startsWith("### ")) {
          inBrief = false;
        } else if (line.trim()) {
          creativeBrief += " " + line.trim();
        }
      }
    }

    creativeBrief = creativeBrief.replace(/\s+/g, " ").trim();

    const filename = filenameMap.get(num);
    if (!filename) {
      console.warn(`  ⚠️  Post ${num}: no filename found in posts-week-1.md, skipping`);
      continue;
    }

    const size = platform === "IG" ? SIZE_IG : SIZE_FB;
    const prompt = buildDallePrompt({ platform, creativeBrief, size });

    tasks.push({
      num, platform, day: platformDay, pillar: pillarRaw,
      hook, filename, creativeBrief, size, prompt,
    });
  }

  return tasks;
}

// ── Step 3: Build DALL-E prompt (NO TEXT backgrounds only) ──────────────────

function buildDallePrompt(opts: {
  platform: "IG" | "FB";
  creativeBrief: string;
  size: string;
}): string {
  const brandStyle = [
    "Premium marketing agency brand style: dark background (#060912 or #0D1117),",
    "teal (#06D6A0) and blue (#3B82F6) accent abstract shapes and gradients.",
    "Clean architectural layout, geometric patterns, subtle grid lines.",
    "No photos of people. No stock photography. No AI/robot imagery.",
    "Professional, restrained, confident aesthetic.",
  ].join(" ");

  const noTextRule = [
    "CRITICAL: NO text, NO letters, NO words, NO numbers, NO brand names,",
    "NO logos, NO typography of any kind.",
    "This is a PURE background image only — abstract shapes and gradients.",
    "The bottom 35% should be darker to accommodate a text overlay bar.",
  ].join(" ");

  const basePrompt = opts.creativeBrief || "abstract professional corporate background";
  const dims = opts.platform === "IG" ? "1080x1080 square" : "1200x630 landscape";

  const fullPrompt = `${brandStyle} ${noTextRule} Create a ${dims} PURE BACKGROUND with NO text for ${opts.platform === "IG" ? "Instagram" : "Facebook"}. ${basePrompt}`;

  return fullPrompt.length > 3800 ? fullPrompt.slice(0, 3800) : fullPrompt;
}

// ── Step 4: Call /api/dalle endpoint ─────────────────────────────────────────

interface DalleResponse {
  url?: string;
  image?: string;
  error?: string;
}

async function generateImage(
  prompt: string,
  size: string,
): Promise<{ type: "url" | "base64"; data: string }> {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 120_000);
  const res = await fetch(`${API_BASE}/api/dalle`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ prompt, size, quality: QUALITY }),
    signal: controller.signal,
  }).finally(() => clearTimeout(timeout));

  const data = (await res.json()) as DalleResponse;

  if (!res.ok || data.error) {
    throw new Error(`DALL-E API error (${res.status}): ${data.error || "Unknown"}`);
  }

  if (data.url) return { type: "url", data: data.url };
  if (data.image) return { type: "base64", data: data.image };

  throw new Error("No image data returned from DALL-E API");
}

// ── Step 5: Download and save image ──────────────────────────────────────────

async function saveImage(
  source: { type: "url" | "base64"; data: string },
  filepath: string,
): Promise<void> {
  if (source.type === "base64") {
    writeFileSync(filepath, Buffer.from(source.data, "base64"));
    return;
  }
  const res = await fetch(source.data);
  if (!res.ok) throw new Error(`Failed to download image: ${res.status}`);
  writeFileSync(filepath, Buffer.from(await res.arrayBuffer()));
}

// ── Step 6 (NEW): Overlay text onto background using Pillow ──────────────────

function runOverlay(
  bgPath: string,
  headline: string,
  subtitle: string,
  outputPath: string,
): { success: boolean; error?: string } {
  const args = [
    OVERLAY_SCRIPT,
    "--bg", bgPath,
    "--headline", headline,
    "--output", outputPath,
  ];
  if (subtitle) {
    args.push("--subtitle", subtitle);
  }

  const result = spawnSync("python3", args, {
    timeout: 30_000,
    encoding: "utf-8",
  });

  if (result.error || result.status !== 0) {
    const errMsg = result.stderr?.trim() || result.error?.message || "Unknown overlay error";
    return { success: false, error: errMsg };
  }

  // Verify output file was created
  if (!existsSync(outputPath)) {
    return { success: false, error: "Overlay script ran but no output file was created" };
  }

  return { success: true };
}

// ── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  console.log("🎨 MetroReach Social Graphics Generator v2 (Text Overlay Pipeline)");
  console.log("═══════════════════════════════════════════════════════════════════\n");

  if (!existsSync(OUTPUT_DIR)) {
    mkdirSync(OUTPUT_DIR, { recursive: true });
  }

  console.log("📋 Parsing content calendar...");
  const tasks = parseCalendarPosts();
  console.log(`  Found ${tasks.length} posts needing graphics\n`);

  if (tasks.length === 0) {
    console.log("No graphics to generate. Done.");
    return;
  }

  // Check server
  console.log("🔌 Checking API endpoint...");
  try {
    const healthCheck = await fetch(`${API_BASE}/api/dalle`, { method: "POST", body: "{}" });
    if (healthCheck.status === 404) {
      throw new Error("API route not found. Is the dev server running?");
    }
  } catch (err: any) {
    if (err.message?.includes("fetch")) {
      console.error("❌ Cannot reach dev server at", API_BASE);
      console.error("   Make sure 'bun run dev' is running on port 3000.");
      process.exit(1);
    }
  }
  console.log("  Server is reachable.\n");

  let success = 0;
  let failed = 0;
  let needsReview = 0;
  const MAX_RETRIES = 2;

  for (let i = 0; i < tasks.length; i++) {
    const task = tasks[i];
    const outputPath = join(OUTPUT_DIR, task.filename);

    if (existsSync(outputPath)) {
      console.log(`⏭️  [${i + 1}/${tasks.length}] Post ${task.num} (${task.platform}): ${task.filename} already exists, skipping`);
      continue;
    }

    console.log(
      `🖼️  [${i + 1}/${tasks.length}] Post ${task.num} (${task.platform} ${task.pillar}): ${task.hook.slice(0, 60)}...`,
    );
    console.log(`    Size: ${task.size}, File: ${task.filename}`);

    let imageGenerated = false;

    for (let attempt = 1; attempt <= MAX_RETRIES; attempt++) {
      try {
        // 1. Generate clean background via DALL-E
        console.log(`    🎲 DALL-E background (attempt ${attempt}/${MAX_RETRIES})...`);
        const imageSource = await generateImage(task.prompt, task.size);

        // Save as temp background
        const bgTmpPath = join(OUTPUT_DIR, `.bg-${task.filename}`);
        await saveImage(imageSource, bgTmpPath);
        console.log(`    💾 Background saved: ${bgTmpPath}`);

        // 2. Overlay text using Pillow (no hallucinations possible)
        console.log(`    🔤 Overlaying text: "${task.hook.slice(0, 50)}..."`);
        const subtitle = "METROREACH MEDIA"; // Brand tagline, always correct
        const overlayResult = runOverlay(bgTmpPath, task.hook, subtitle, outputPath);

        // Clean up temp background
        try { unlinkSync(bgTmpPath); } catch { /* best-effort */ }

        if (overlayResult.success) {
          console.log(`    ✅ Overlay complete → ${task.filename}`);
          console.log(`    ✅ AUTO-PASS: Text is code-generated (no hallucinations possible)`);
          success++;
          imageGenerated = true;
          break;
        } else {
          console.log(`    ⚠️  Overlay failed: ${overlayResult.error}`);
          console.log(`    🔄 Falling back to DALL-E text generation + audit...`);

          // Fallback: use DALL-E with text directly + audit
          // Clean up the temp bg if it still exists
          try { unlinkSync(bgTmpPath); } catch { /* best-effort */ }
        }
      } catch (err: any) {
        console.error(`    ❌ Error (attempt ${attempt}): ${err.message}`);
      }

      if (attempt < MAX_RETRIES) {
        await sleep(1500);
      }
    }

    // If overlay failed on all attempts, try DALL-E direct text generation
    if (!imageGenerated) {
      console.log(`    🔄 Attempting DALL-E text generation fallback...`);
      for (let attempt = 1; attempt <= 3; attempt++) {
        try {
          // Build a text-inclusive prompt for DALL-E
          const fallbackPrompt = [
            task.prompt.replace(/NO text.*?background image only[^.]*\./gi, ""),
            `CRITICAL: Display the text "${task.hook}" prominently.`,
            `The brand name "METROREACH MEDIA" must appear correctly.`,
            `No other brand names. No garbled text.`,
          ].join(" ");

          const imageSource = await generateImage(fallbackPrompt, task.size);
          await saveImage(imageSource, outputPath);

          console.log(`    🔍 Auditing DALL-E text image (attempt ${attempt})...`);
          const auditResult = await auditImage(outputPath);

          if (auditResult.status === "PASS") {
            console.log(`    ✅ Audit passed: ${auditResult.textFound}`);
            success++;
            imageGenerated = true;
            break;
          } else {
            console.log(`    ❌ Audit failed: ${auditResult.failureReason}`);
            try { unlinkSync(outputPath); } catch { /* cleanup */ }
          }
        } catch (err: any) {
          console.error(`    ❌ Fallback error (attempt ${attempt}): ${err.message}`);
        }
        if (attempt < 3) await sleep(1500);
      }
    }

    if (!imageGenerated) {
      console.log(`    🚨 All attempts failed — marking for manual review`);
      needsReview++;
      failed++;
    }

    if (i < tasks.length - 1) {
      console.log("    ⏳ Waiting 2s before next request...");
      await sleep(2000);
    }
  }

  console.log(`\n✅ Done. ${success} generated (overlay), ${failed} failed (${needsReview} need manual review), ${tasks.length - success - failed} skipped.`);
  if (needsReview > 0) {
    console.log(`\n⚠️  ${needsReview} images need manual review. Check public/social/ for missing files.`);
  }
}

main().catch((err) => {
  console.error("Fatal error:", err.message);
  process.exit(1);
});
